### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by Sebastian-Maier** [Foxi352/homebridge-smarthomeng#12]
Will there be a new release of homebridge-smarthomeng (as NPM package)?

**Comment by Foxi352** [comment]
After a break due to lack of time, i am dedicated to this project again. The old code was inspired by the then existing knx example and was a mess to maintain.

At the moment a complete rewrite from scratch is being done. You can monitor the progress in the v2-dev branch.
So i expect a first working v2.0.0 version (on npmjs) soon. In this new code it will be a lot easier to add support for more accessories.
